apiVersion: apps/v1
kind: Deployment
metadata:
  name: ambient-exporter
spec:
  template:
    spec:
      containers:
      - name: server
        image: ghcr.io/ianunruh/ambient-exporter:v1.0.0
        envFrom:
        - secretRef:
            name: ambient-exporter
        ports:
        - name: metrics
          containerPort: 9090
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 128Mi
