apiVersion: apps/v1
kind: Deployment
metadata:
  name: ambient-exporter
spec:
  template:
    spec:
      containers:
      - name: server
        image: ghcr.io/ianunruh/ambient-exporter:v1.1.0
        envFrom:
        - secretRef:
            name: ambient-exporter
        ports:
        - name: metrics
          containerPort: 9090
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
            add:
            - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
