apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: ambient-exporter
resources:
- deployment.yaml
- service.yaml
- service-monitor.yaml
